---
apiVersion: v1
kind: Namespace
metadata:
  name: conjur-ce

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: conjur-community
  namespace: conjur-ce
  labels:
    app: conjur-ce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: conjur-ce
  template:
    metadata:
      labels:
        app: conjur-ce
    spec:
      containers:
      - name: conjur-ce-database
        image: postgres:9.3
        ports:
          - name: postgres1
            containerPort: 5432
          - name: postgres2
            containerPort: 5433
      - name: conjur-master
        image: cyberark/conjur
        env:
          - name: DATABASE_URL
            value: "postgres://postgres@conjur-ce-database.conjur-ce.svc.cluster.local/postgres"
          - name: CONJUR_DATA_KEY
            value: "Eb/WhB7csC3v68/h4Ye6l/SpSBM5OwqhEfJm9JFFYP0="
        ports:
          - name: conjur-ce-ui
            containerPort: 80
        args: ["server"]
      - name: conjur-cli
        image: conjurinc/cli5
        env:
          - name: CONJUR_APPLIANCE_URL
            value: http://conjur-ce-ui.conjur-ce.svc.cluster.local
          - name: CONJUR_ACCOUNT
            value: 
          - name: CONJUR_AUTHN_API_KEY
            value: 
          - name: CONJUR_AUTHN_LOGIN
            value:
        command: ["sleep"]
        args: ["infinity"]
        
---
apiVersion: v1
kind: Service
metadata:
  name: conjur-ce-ui
  namespace: conjur-ce
spec:
  ports:
  - name: conjur-ui
    port: 80
    targetPort: 80
  selector:
    app: conjur-ce
  type: NodePort
  
---
apiVersion: v1
kind: Service
metadata:
  name: conjur-ce-database
  namespace: conjur-ce
spec:
  ports:
  - name: postgres1
    port: 5432
    targetPort: 5432
  - name: postgres2
    port: 5433
    targetPort: 5433
  selector:
    app: conjur-ce
  type: NodePort