---
apiVersion: v1
kind: Namespace
metadata:
  name: conjur-ce

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: conjur-cluster
  namespace: conjur-ce
  labels:
    app: conjur-community
spec:
  replicas: 1
  selector:
    matchLabels:
      app: conjur
  template:
    metadata:
      labels:
        app: conjur
    spec:
      containers:
      - name: conjur-database
        imagePullPolicy: Always
        image: postgres:9.3
        ports:
          - name: postgres1
            containerPort: 5432
          - name: postgres2
            containerPort: 5433
        readinessProbe:
          tcpSocket:
            port: 5432
          initialDelaySeconds: 20
          periodSeconds: 10
      - name: conjur-master
        imagePullPolicy: Always
        image: cyberark/conjur
        env:
          - name: DATABASE_URL
            value: "postgres://postgres@conjur.conjur-ce.svc.cluster.local/postgres"
          - name: CONJUR_DATA_KEY
            value: "Eb/WhB7csC3v68/h4Ye6l/SpSBM5OwqhEfJm9JFFYP0="
        ports:
          - name: conjur-ui
            containerPort: 80
        args: ["server"]      
      - name: conjur-cli
        imagePullPolicy: Always
        image: conjurinc/cli5
        command: ["sleep"]
        args: ["infinity"]
        
---
apiVersion: v1
kind: Service
metadata:
  name: conjur
  namespace: conjur-ce
spec:
  ports:
  - name: conjur-ui
    port: 80
    targetPort: 80
  - name: postgres1
    port: 5432
    targetPort: 5432
  - name: postgres2
    port: 5433
    targetPort: 5433
  selector:
    app: conjur
  type: NodePort